puts 'seeding portuguese universities...'

pt_universities = [
  { name: 'Universidade do Porto' },
  { name: 'Universidade de Coimbra' },
  { name: 'Universidade Técnica de Lisboa' },
  { name: 'Universidade de Lisboa' },
  { name: 'Universidade do Minho' },
  { name: 'Universidade Nova de Lisboa' },
  { name: 'Universidade de Évora' },
  { name: 'Universidade de Aveiro' },
  { name: 'Universidade Católica Portuguesa' },
  { name: 'Instituto Superior Politécnico de Viseu' },
  { name: 'Universidade da Beira Interior' },
  { name: 'Instituto Politécnico de Leiria' },
  { name: 'Universidade do Algarve' },
  { name: 'Instituto Politécnico do Porto' },
  { name: 'Universidade de Tras os Montes e Alto Douro' },
  { name: 'Universidade da Madeira' },
  { name: 'Universidade dos Açores' },
  { name: 'Instituto Politécnico de Lisboa' },
  { name: 'Instituto Politécnico de Bragança' },
  { name: 'Universidade Fernando Pessoa' },
  { name: 'Universidade Lusófona de Humanidades e Tecnologias' },
  { name: 'Instituto Politécnico de Setúbal' },
  { name: 'Instituto Politécnico de Tomar' },
  { name: 'Instituto Politécnico de Viana do Castelo' },
  { name: 'Instituto Politécnico de Beja' },
  { name: 'ISCTE Instituto Universitário de Lisboa' },
  { name: 'Escola Superior de Saúde de Portalegre' },
  { name: 'Instituto Superior de Psicologia Aplicada' },
  { name: 'Instituto Politécnico de Castelo Branco' },
  { name: 'Instituto Politécnico de Santarém' },
  { name: 'Instituto Piaget' },
  { name: 'Instituto Politécnico de Coimbra' },
  { name: 'Instituto Superior Politécnico de Gaya' },
  { name: 'Instituto Politécnico de Portalegre' },
  { name: 'Instituto Politécnico de Guarda' },
  { name: 'Universidade Aberta' },
  { name: 'Cooperativa de Ensino Superior, Politécnico e Universitario' },
  { name: 'Instituto Superior da Maia' },
  { name: 'Instituto Politécnico do Cavado e do Ave' },
  { name: 'Instituto de Artes Visuais, Design e Marketing' },
  { name: 'Escola Superior de Educação de Coimbra' },
  { name: 'Universidade Autónoma de Lisboa' },
  { name: 'Universidades Lusíada de Lisboa' },
  { name: 'Escola Superior de Artes e Design Matosinhos' },
  { name: 'Instituto Superior de Engenharia de Lisboa' },
  { name: 'Escola Superior de Saúde Egas Moniz' },
  { name: 'Universidade Portucalense Infante D Henrique' },
  { name: 'Instituto Superior de Linguas e Administração Lisboa' },
  { name: 'Escola Superior de Música e Artes do Espectaculo' },
  { name: 'Instituto Superior de Linguas e Administração Leiria' },
  { name: 'Universidade Lusofona do Porto' },
  { name: 'Escola Superior de Hotelaria e Turismo do Estoril' },
  { name: 'Escola Superior Agrária de Coimbra' },
  { name: 'Instituto Superior de Engenharia de Coimbra' },
  { name: 'Escola Superior de Enfermagem de Coimbra' },
  { name: 'Instituto Portugues de Administração de Marketing' },
  { name: 'Universidades Lusíada do Porto' },
  { name: 'Escola Superior de Educação Paula Frassinetti' },
  { name: 'Instituto Superior de Gestão' },
  { name: 'Instituto Superior Miguel Torga' },
  { name: 'Academia Militar Portugal' },
  { name: 'Escola Superior Artistica do Porto' },
  { name: 'Instituto Superior Dom Afonso III' },
  { name: 'Universidades Lusíada de Famalicão' },
  { name: 'Instituto Superior de Educação e Ciências' },
  { name: 'Universidade Atlântica' },
  { name: 'Escola Superior de Tecnología e Gestão de Portalegre' },
  { name: 'Escola Superior de Saúde de Alcoitão' },
  { name: 'Escola Superior de Enfermagem de Lisboa' },
  { name: 'Instituto Superior Novas Profissões' },
  { name: 'Escuela Universitaria das Artes de Coimbra' },
  { name: 'Escola Náutica Infante Dom Henrique' },
  { name: 'Escola Superior de Enfermagem do Porto' },
  { name: 'Instituto Superior de Ciências Empresariais e Turismo' },
  { name: 'Escola Superior de Educação de Portalegre' },
  { name: 'Instituto Superior de Contabilidade e Administração de Coimbra' },
  { name: 'Instituto Superior de Saúde do Alto Ave' },
  { name: 'Escola Superior Agrária de Elvas' },
  { name: 'Escola Superior Gallaecia' },
  { name: 'Escola Superior de Educação João de Deus' },
  { name: 'Escola Superior de Tecnología da Saúde de Coimbra' },
  { name: 'Instituto Superior de Ciências da Informação e de Administração' },
  { name: 'Instituto Superior Autónomo de Estudos Politécnicos' },
  { name: 'Instituto Superior de Tecnologías Avançadas' },
  { name: 'Instituto Superior Bissaya Barreto' },
  { name: 'Escola Universitária Vasco da Gama' },
  { name: 'Instituto de Estudos Superiores Financeiros e Fiscais' },
  { name: 'Instituto Superior de Administração e Gestão' },
  { name: 'Instituto Superior de Paços de Brandão' },
  { name: 'Escola Naval da Marinha' },
  { name: 'Instituto de Estudos Superiores de Fafe' },
  { name: 'Escola Superior Artistica do Porto Guimaraes' },
  { name: 'Escola Superior de Tecnologías e Artes de Lisboa' },
  { name: 'Instituto Superior de Comunicaçao Empresarial' },
  { name: 'Instituto Superior de Ciências Educativas' },
  { name: 'Escola Superior de Actividades Imobiliarias' },
  { name: 'Instituto Superior de Entre Douro e Vouga' },
  { name: 'Escola Superior de Educação Almeida Garret' },
  { name: 'Escola Superior de Educadores de Infância Maria Ulrich' },
  { name: 'Instituto Superior de Serviço Social do Porto' },
  { name: 'Escola Superior de Enfermagem de Vila Real' },
  { name: 'Escola Superior de Educação de Torres Novas' },
  { name: 'Instituto Superior de Administração e Línguas da Madeira' },
  { name: 'Instituto Superior de Gestão Bancaria' },
  { name: 'Escola Superior de Enfermagem de São José de Cluny' },
  { name: 'Instituto Superior de Ciências Policiais e Segurança Interna' },
  { name: 'Escola Superior de Enfermagem São Francisco das Misericórdias' },
  { name: 'Escola Superior de Enfermagem Dr José Timóteo Montalvão Machado' },
  { name: 'Universidade dos Açores' },
  { name: 'Escola Superior de Enfermagem de Angra do Heroismo' },
  { name: 'Escola Superior de Enfermagem de Santa Maria' }
]
 
pt_universities.each do |university|
  Institution.where(university).first_or_create!
end
