require_relative 'seeds/users.rb'
require_relative 'seeds/institutions.rb'
require_relative 'seeds/courses.rb'
require_relative 'seeds/subjects.rb'
#require_relative 'seeds/statements.rb'
#require_relative 'seeds/projects.rb'
